

import 'package:intermediate_lesson_12/modal/food_model.dart';


List<FoodModal> foodList = <FoodModal>[
  //15 * 5= 75
 
  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/chinese_food.jpg",
      name: "ဆူရှီ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food1.jpg",
      name: "အကြော်စုံ  ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food2.jpg",
      name: "မုန့်ဟင်းခါး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/fried_rice.jpg",
      name: "ထမင်းကြော်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားကင်စုံ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/japanese_noodle.jpg",
      name: "ကြေးအိုး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/suisine.jpg",
      name: "ရေညှိထမင်းလိပ်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/chinese_food.jpg",
      name: "ဆူရှီ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food1.jpg",
      name: "အကြော်စုံ  ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food2.jpg",
      name: "မုန့်ဟင်းခါး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/fried_rice.jpg",
      name: "ထမင်းကြော်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားကင်စုံ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/japanese_noodle.jpg",
      name: "ကြေးအိုး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/suisine.jpg",
      name: "ရေညှိထမင်းလိပ်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/chinese_food.jpg",
      name: "ဆူရှီ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food1.jpg",
      name: "အကြော်စုံ  ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food2.jpg",
      name: "မုန့်ဟင်းခါး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/fried_rice.jpg",
      name: "ထမင်းကြော်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားကင်စုံ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/japanese_noodle.jpg",
      name: "ကြေးအိုး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/suisine.jpg",
      name: "ရေညှိထမင်းလိပ်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/chinese_food.jpg",
      name: "ဆူရှီ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food1.jpg",
      name: "အကြော်စုံ  ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food2.jpg",
      name: "မုန့်ဟင်းခါး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/fried_rice.jpg",
      name: "ထမင်းကြော်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားကင်စုံ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/japanese_noodle.jpg",
      name: "ကြေးအိုး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/suisine.jpg",
      name: "ရေညှိထမင်းလိပ်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/chinese_food.jpg",
      name: "ဆူရှီ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food1.jpg",
      name: "အကြော်စုံ  ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food2.jpg",
      name: "မုန့်ဟင်းခါး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/fried_rice.jpg",
      name: "ထမင်းကြော်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားကင်စုံ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/japanese_noodle.jpg",
      name: "ကြေးအိုး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/suisine.jpg",
      name: "ရေညှိထမင်းလိပ်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/chinese_food.jpg",
      name: "ဆူရှီ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food1.jpg",
      name: "အကြော်စုံ  ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food2.jpg",
      name: "မုန့်ဟင်းခါး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/fried_rice.jpg",
      name: "ထမင်းကြော်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားကင်စုံ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/japanese_noodle.jpg",
      name: "ကြေးအိုး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/suisine.jpg",
      name: "ရေညှိထမင်းလိပ်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/chinese_food.jpg",
      name: "ဆူရှီ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food1.jpg",
      name: "အကြော်စုံ  ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food2.jpg",
      name: "မုန့်ဟင်းခါး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/fried_rice.jpg",
      name: "ထမင်းကြော်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားကင်စုံ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/japanese_noodle.jpg",
      name: "ကြေးအိုး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/suisine.jpg",
      name: "ရေညှိထမင်းလိပ်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/chinese_food.jpg",
      name: "ဆူရှီ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food1.jpg",
      name: "အကြော်စုံ  ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food2.jpg",
      name: "မုန့်ဟင်းခါး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/fried_rice.jpg",
      name: "ထမင်းကြော်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားကင်စုံ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/japanese_noodle.jpg",
      name: "ကြေးအိုး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/suisine.jpg",
      name: "ရေညှိထမင်းလိပ်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/chinese_food.jpg",
      name: "ဆူရှီ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food1.jpg",
      name: "အကြော်စုံ  ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food2.jpg",
      name: "မုန့်ဟင်းခါး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/fried_rice.jpg",
      name: "ထမင်းကြော်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားကင်စုံ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/japanese_noodle.jpg",
      name: "ကြေးအိုး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/suisine.jpg",
      name: "ရေညှိထမင်းလိပ်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/chinese_food.jpg",
      name: "ဆူရှီ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/food.jpg",
      name: "ထမင်းလိပ်နှင့်သုံးထပ်သား",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/food1.jpg",
      name: "အကြော်စုံ  ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/food2.jpg",
      name: "မုန့်ဟင်းခါး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/fried_rice.jpg",
      name: "ထမင်းကြော်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Burmese Food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားကင်စုံ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/japanese_noodle.jpg",
      name: "ကြေးအိုး",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),
  FoodModal(
      imageUrl: "images/suisine.jpg",
      name: "ရေညှိထမင်းလိပ်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
  FoodModal(
      imageUrl: "images/sushi.jpg",
      name: "အသားစုံကင်",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "Japanese food",
      isPromo: "",
      delivery: "",
      deliveryFeed: ""),

  FoodModal(
      imageUrl: "images/tomato_chip_and_cocacola.jpg",
      name: "ကိုကာကိုလာနှင့် အာလူးကြော် ",
      howlong: 35,
      distance: 35,
      rate: 4.5,
      kind: "KFC food",
      isPromo: "PROMO",
      delivery: "Delivery Free",
      deliveryFeed: "Ks700,00 off Delivery"),
];
